export { default as About } from "./About"
export { default as Banner } from "./Banner"
export { default as LeftSide } from "./LeftSide"
export { default as Navbar } from "./Navbar"
export { default as Projects } from "./Projects"
export { default as RightSide } from "./RightSide"
export { default as SectionTitle } from "./SectionTitle"