name: 🚀 Nuxt

on:
  push:
    branches: ['*']

jobs:
  # Checkout, Setup and Install Dependencies
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Set up pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'pnpm'
          cache-dependency-path: portfolio/pnpm-lock.yaml

      - name: Install Node.js Dependencies
        run: pnpm -C portfolio install

  # Biome
  biome:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Set up pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'pnpm'
          cache-dependency-path: portfolio/pnpm-lock.yaml

      - name: Install Node.js Dependencies
        run: pnpm -C portfolio install

      - name: Biome
        run: pnpm -C portfolio run check

  # Typeslint
  typeslint:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Set up pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'pnpm'
          cache-dependency-path: portfolio/pnpm-lock.yaml

      - name: Install Node.js Dependencies
        run: pnpm -C portfolio install

      - name: Typeslint
        run: pnpm -C portfolio run typeslint
        
  # Stylelint
  stylelint:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Set up pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'pnpm'
          cache-dependency-path: portfolio/pnpm-lock.yaml

      - name: Install Node.js Dependencies
        run: pnpm -C portfolio install

      - name: Stylelint
        run: pnpm -C portfolio run slint

  # Build Assets
  build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Set up pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'pnpm'
          cache-dependency-path: portfolio/pnpm-lock.yaml

      - name: Install Node.js Dependencies
        run: pnpm -C portfolio install

      - name: Build Assets
        run: pnpm -C portfolio run build

  # Run Vitests
  test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Set up pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'pnpm'
          cache-dependency-path: portfolio/pnpm-lock.yaml

      - name: Install Node.js Dependencies
        run: pnpm -C portfolio install

      - name: Execute tests via Vitest
        run: pnpm -C portfolio run tests
